# Form implementation generated from reading ui file 'design/ui_files/create_note.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from loguru import logger

class CreateNoteWindowDesign(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setFixedSize(370, 169)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.create_note = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_note.setGeometry(QtCore.QRect(10, 90, 351, 32))
        self.create_note.setObjectName("create_note")
        self.note_title = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.note_title.setGeometry(QtCore.QRect(10, 10, 351, 71))
        self.note_title.setObjectName("note_title")
        self.close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.close.setGeometry(QtCore.QRect(10, 130, 351, 32))
        self.close.setObjectName("close")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        logger.success(f'Дизайн вікна створення нонатки завантажено у {mainWindow}')

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "NoteBook"))
        self.create_note.setText(_translate("mainWindow", "Створити нонатку"))
        self.note_title.setPlaceholderText(_translate("mainWindow", "Заголовок нонатки"))
        self.close.setText(_translate("mainWindow", "Закрити"))
