# Form implementation generated from reading ui file 'src/design/ui_files/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from loguru import logger


class MainWindowDesign(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setFixedSize(800, 477)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.delete_all_notes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_all_notes.setGeometry(QtCore.QRect(10, 360, 781, 32))
        self.delete_all_notes.setObjectName("delete_all_notes")
        self.version = QtWidgets.QLabel(parent=self.centralwidget)
        self.version.setGeometry(QtCore.QRect(20, 400, 761, 71))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.version.setFont(font)
        self.version.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.version.setObjectName("version")
        self.delete_note = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_note.setGeometry(QtCore.QRect(10, 280, 391, 32))
        self.delete_note.setObjectName("delete_note")
        self.open_note = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_note.setGeometry(QtCore.QRect(413, 280, 381, 32))
        self.open_note.setObjectName("open_note")
        self.notes = QtWidgets.QListWidget(parent=self.centralwidget)
        self.notes.setGeometry(QtCore.QRect(10, 10, 781, 261))
        self.notes.setObjectName("notes")
        self.create_note = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_note.setGeometry(QtCore.QRect(10, 320, 781, 32))
        self.create_note.setObjectName("create_note")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        logger.success(f'Дизайн головного вікна завантажено у {mainWindow}')

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "NoteBook"))
        self.delete_all_notes.setText(_translate("mainWindow", "Видалити всі нонатки"))
        self.version.setText(_translate("mainWindow", "Версія 0.0.0"))
        self.delete_note.setText(_translate("mainWindow", "Видалити нонатку"))
        self.open_note.setText(_translate("mainWindow", "Відкрити нонатку"))
        self.create_note.setText(_translate("mainWindow", "Створити нонатку"))
