# Form implementation generated from reading ui file 'design/ui_files/note_edit.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from loguru import logger


class NoteEditWindowDesign(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.close.setGeometry(QtCore.QRect(10, 560, 781, 32))
        self.close.setObjectName("close")
        self.note_title = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.note_title.setGeometry(QtCore.QRect(10, 10, 781, 71))
        self.note_title.setObjectName("note_title")
        self.note_content = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.note_content.setGeometry(QtCore.QRect(10, 90, 781, 461))
        self.note_content.setObjectName("note_content")
        self.note_content.setPlaceholderText('Текст нонатки')
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        logger.success(f'Дизайн вікна редагування нонатки завантажено у {mainWindow}')

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "NoteBook"))
        self.close.setText(_translate("mainWindow", "Закрити"))
        self.note_title.setPlaceholderText(_translate("mainWindow", "Заголовок нонатки"))
